<?xml version="1.0" encoding="utf-8"?>
<TestRun id="4025896e-2084-4723-8dec-97d7d8562b9d" name="McNaggur@DESKTOP-VFNHS4J 2019-06-11 23:45:26:673" runUser="DESKTOP-VFNHS4J\McNaggur" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2019-06-11T23:45:26.6731031+01:00" queuing="2019-06-11T23:45:26.6731031+01:00" start="2019-06-11T23:45:25.2290944+01:00" finish="2019-06-11T23:45:26.6950182+01:00" />
  <TestSettings name="default" id="b66f704d-5462-4d5c-a43b-4d5f08bcfb34">
    <Deployment runDeploymentRoot="McNaggur_DESKTOP-VFNHS4J_2019-06-11_23_45_26_673" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="4a618d2a-fbd2-41ed-9b6d-85739888bdf5" testId="69db8c24-0749-609c-88a5-31aac5679d61" testName="CreatePostTest" computerName="DESKTOP-VFNHS4J" duration="00:00:00.5778733" startTime="2019-06-11T23:45:25.6701773+01:00" endTime="2019-06-11T23:45:26.2492829+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="4a618d2a-fbd2-41ed-9b6d-85739888bdf5">
      <Output>
        <ErrorInfo>
          <Message>Test method AutomationTests.UnitTest1.CreatePostTest threw exception: &#xD;
System.Net.Http.HttpRequestException: Unexpected response status code: NotFound</Message>
          <StackTrace>    at AutomationTests.Services.JsonApiService.&lt;GetAsync&gt;d__2`1.MoveNext() in J:\Projects\TechTest\AutomationTests\Services\JsonApiService.cs:line 30&#xD;
--- End of stack trace from previous location where exception was thrown ---&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;
   at AutomationTests.UnitTest1.&lt;CreatePostTest&gt;d__3.MoveNext() in J:\Projects\TechTest\AutomationTests\UnitTest1.cs:line 52&#xD;
--- End of stack trace from previous location where exception was thrown ---&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="b7b37fb1-bf72-4585-8024-3b23af9f8c4e" testId="ac019bae-f824-cdef-de5b-635d98213a13" testName="DeletePostTest" computerName="DESKTOP-VFNHS4J" duration="00:00:00.3431030" startTime="2019-06-11T23:45:26.2492829+01:00" endTime="2019-06-11T23:45:26.5922454+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b7b37fb1-bf72-4585-8024-3b23af9f8c4e">
      <Output>
        <ErrorInfo>
          <Message>Expected retrievedPost to be &lt;null&gt;, but found &#xD;
&#xD;
AutomationTests.Types.Post&#xD;
{&#xD;
   Body = "quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto"&#xD;
   Id = 1&#xD;
   Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"&#xD;
   UserId = 1&#xD;
}.</Message>
          <StackTrace>   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\Workspaces\fluentassertions\src\FluentAssertions\Execution\LateBoundTestFramework.cs:line 13&#xD;
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\Workspaces\fluentassertions\src\FluentAssertions\Execution\TestFrameworkProvider.cs:line 40&#xD;
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\Workspaces\fluentassertions\src\FluentAssertions\Execution\DefaultAssertionStrategy.cs:line 25&#xD;
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\Workspaces\fluentassertions\src\FluentAssertions\Execution\AssertionScope.cs:line 185&#xD;
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\Workspaces\fluentassertions\src\FluentAssertions\Execution\AssertionScope.cs:line 200&#xD;
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeNull(String because, Object[] becauseArgs) in C:\Workspaces\fluentassertions\src\FluentAssertions\Primitives\ReferenceTypeAssertions.cs:line 44&#xD;
   at AutomationTests.UnitTest1.&lt;DeletePostTest&gt;d__4.MoveNext() in J:\Projects\TechTest\AutomationTests\UnitTest1.cs:line 77&#xD;
--- End of stack trace from previous location where exception was thrown ---&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="2cbece98-f8d7-4659-84a6-1295aced4bf6" testId="efe8e29c-ae30-d6a2-acb3-6d82b2c8a248" testName="GetAllPostsTest" computerName="DESKTOP-VFNHS4J" duration="00:00:00.2201256" startTime="2019-06-11T23:45:25.4185861+01:00" endTime="2019-06-11T23:45:25.6651919+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2cbece98-f8d7-4659-84a6-1295aced4bf6" />
  </Results>
  <TestDefinitions>
    <UnitTest name="CreatePostTest" storage="j:\projects\techtest\automationtests\bin\debug\automationtests.dll" id="69db8c24-0749-609c-88a5-31aac5679d61">
      <Execution id="4a618d2a-fbd2-41ed-9b6d-85739888bdf5" />
      <TestMethod codeBase="J:\Projects\TechTest\AutomationTests\bin\Debug\AutomationTests.dll" adapterTypeName="executor://mstestadapter/v2" className="AutomationTests.UnitTest1" name="CreatePostTest" />
    </UnitTest>
    <UnitTest name="DeletePostTest" storage="j:\projects\techtest\automationtests\bin\debug\automationtests.dll" id="ac019bae-f824-cdef-de5b-635d98213a13">
      <Execution id="b7b37fb1-bf72-4585-8024-3b23af9f8c4e" />
      <TestMethod codeBase="J:\Projects\TechTest\AutomationTests\bin\Debug\AutomationTests.dll" adapterTypeName="executor://mstestadapter/v2" className="AutomationTests.UnitTest1" name="DeletePostTest" />
    </UnitTest>
    <UnitTest name="GetAllPostsTest" storage="j:\projects\techtest\automationtests\bin\debug\automationtests.dll" id="efe8e29c-ae30-d6a2-acb3-6d82b2c8a248">
      <Execution id="2cbece98-f8d7-4659-84a6-1295aced4bf6" />
      <TestMethod codeBase="J:\Projects\TechTest\AutomationTests\bin\Debug\AutomationTests.dll" adapterTypeName="executor://mstestadapter/v2" className="AutomationTests.UnitTest1" name="GetAllPostsTest" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="69db8c24-0749-609c-88a5-31aac5679d61" executionId="4a618d2a-fbd2-41ed-9b6d-85739888bdf5" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="ac019bae-f824-cdef-de5b-635d98213a13" executionId="b7b37fb1-bf72-4585-8024-3b23af9f8c4e" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="efe8e29c-ae30-d6a2-acb3-6d82b2c8a248" executionId="2cbece98-f8d7-4659-84a6-1295aced4bf6" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="3" executed="3" passed="1" failed="2" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>